### ISSUE TITLE
errors, stuck after last pull

### ISSUE THREAD

**Issue by webthingee** [Lullabot/copelandia#26]
tried to run grunt server

`... Uhoh. Got error listen EADDRINUSE ...
Error: listen EADDRINUSE
    at errnoException (net.js:878:11)
    at Server._listen2 (net.js:1016:14)
    at listen (net.js:1038:10)
    at Server.listen (net.js:1104:5)
    at Server.listen (/Users/webthingee/Sites/lullabot/arts/copelandia/clients/angularjs/node_modules/grunt-contrib-livereload/node_modules/tiny-lr/lib/server.js:133:15)
    at Object.startLRServer (/Users/webthingee/Sites/lullabot/arts/copelandia/clients/angularjs/node_modules/grunt-contrib-livereload/lib/utils.js:21:11)
    at Object.<anonymous> (/Users/webthingee/Sites/lullabot/arts/copelandia/clients/angularjs/node_modules/grunt-contrib-livereload/tasks/livereload.js:44:20)
    at Object.thisTask.fn (/Users/webthingee/Sites/lullabot/arts/copelandia/clients/angularjs/node_modules/grunt/lib/grunt/task.js:78:16)
    at Object.<anonymous> (/Users/webthingee/Sites/lullabot/arts/copelandia/clients/angularjs/node_modules/grunt/lib/util/task.js:282:30)
    at Task.runTaskFn (/Users/webthingee/Sites/lullabot/arts/copelandia/clients/angularjs/node_modules/grunt/lib/util/task.js:235:24)`

**Comment by sirkitree** [comment]
This is a problem with livereload, you already have something else running it and therefore the default address is in use. Figure out which program is running it already and close that down first.

**Comment by webthingee** [comment]
Yep, looks like live.app runs on that port.

ty
